Repository humanmade/aws-analytics, pull requests merged in 2021-08, with the labels that each got.

#234 Add transform rules to personalization block
  inc/blocks/personalization/index.js
  inc/blocks/personalization/transforms.js
Labels: backport v4-branch

#233 Add full list of countries, and update select input display and logic
  README.md
  inc/audiences/namespace.php
  inc/utils/namespace.php
  src/audiences/ui/components/rule.js
Labels: backport v4-branch

#237 Release 4.1.0
  plugin.php
Labels: backport v4-branch

#241 Release 4.1.1
  plugin.php
Labels: backport v4-branch

#243 Use intval to round percentages
  inc/audiences/namespace.php
Labels: backport v4-branch

#245 Release 4.1.2
  plugin.php
Labels: backport v4-branch

#247 Fixing fatal parameter type in call to get_estimate
  inc/audiences/rest_api/namespace.php
Labels: backport v4-branch

#249 Release 4.1.3
  plugin.php
Labels: backport v4-branch

#251 Sync cached estimates and total and round to nearest hour
  inc/audiences/namespace.php
  inc/utils/namespace.php
Labels: backport v4-branch

#253 Release 4.2.0
  plugin.php
Labels: backport v4-branch

#255 Fix search attribute value
  inc/namespace.php
  src/analytics.js
Labels: backport v4-branch

#257 Release 4.2.1
  plugin.php
Labels: backport v4-branch

#259 Use polyfills.io to fix IE compat issue with ES6 features
  inc/namespace.php
Labels: backport v4-branch, backport v3-branch

#262 Release 3.0.4
  plugin.php
Labels: backport v3-branch

#264 Release 4.2.2
  plugin.php
Labels: backport v4-branch
