Repository humanmade/aws-analytics, pull requests merged in 2022-03, with the labels that each got.

#345 Standalone filters
  inc/namespace.php
  inc/utils/namespace.php
Labels: backport v4-5-branch

#352 Load XBs instantly
  inc/namespace.php
  src/analytics.js
  src/experiments.js
Labels: backport v4-4-branch, backport v4-5-branch

#353 Fix request ID logging behaviour
  src/analytics.js
Labels: backport v4-5-branch

#349 Don't load experiments sidebar if no tests for current post type
  inc/experiments/namespace.php
Labels: backport v4-5-branch

#360 Escape unicode in attributes
  src/utils/index.js
Labels: backport v4-0-branch, backport v4-1-branch, backport v4-3-branch, backport v4-4-branch, backport v4-5-branch
