Repository humanmade/aws-analytics, pull requests merged in 2022-05, with the labels that each got.

#392 [Backport v4-4-branch] Switch to intersection observers for tracking XB views
  src/analytics.js
  src/experiments.js
Labels: backport v4-0-branch, backport v4-1-branch, backport v4-3-branch

#393 [Backport v4-3-branch] Switch to intersection observers for tracking XB views
  src/analytics.js
  src/experiments.js
Labels: backport v4-0-branch, backport v4-1-branch

#405 Show dashboard links with correct user permissions
  inc/dashboard/namespace.php
  src/accelerate/components/Dashboard.tsx
  src/accelerate/components/Hero.tsx
  src/util.ts
Labels: backport v4-5-branch, backport v4-6-branch

#410 Don't show metrics when the value is "infinity".
  src/accelerate/components/Insight.tsx
Labels: backport v4-4-branch, backport v4-5-branch, backport v4-6-branch
