Repository humanmade/aws-analytics, pull requests merged in 2022-11, with the labels that each got.

#531 Load images when Gaussholder is active.
  src/ab-test-preview.js
  src/experiments.js
  src/preview/altis-xb-preview.js
Labels: backport v4-4-branch, backport v4-5-branch, backport v4-6-branch

#535 Backport 531 to v4-6 branch
  src/ab-test-preview.js
  src/experiments.js
Labels: backport v4-4-branch, backport v4-5-branch

#541 Only set taxonomy parameters when not searching
  inc/namespace.php
Labels: backport v4-6-branch
